version: "3.8"

services:
  db:
    image: "mysql:latest"
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - '3308:3306'
    expose:
      - '3306'
    environment:
      MYSQL_DATABASE: 'fleetio'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'

volumes:
  db_data:
